import z from "zod";

const nonEmptyString = z.string().trim().min(1);

const envSchema = z.object({
  NEXT_PUBLIC_SAVING_CIRCLES_CONTRACT_ADDRESS: z.string(),
  NEXT_PUBLIC_SAVING_CIRCLES_VIEWER_CONTRACT_ADDRESS: z.string(),
  NEXT_PUBLIC_BREAD_TOKEN_ADDRESS: z.string(),
  NEXT_PUBLIC_DELEGATED_SAVING_CIRCLES_CONTRACT_ADDRESS: z.string().optional(),
  NEXT_PUBLIC_SAVING_CIRCLES_CONTRACT_CREATION_BLOCK: z.string(),
  NEXT_PUBLIC_TARGET_NETWORK: z
    .enum(["local", "gnosis", "sepolia"])
    .default("gnosis"),
  NEXT_PUBLIC_LOCAL_RPC_URL: z.string().optional(),
  NEXT_PUBLIC_GNOSIS_RPC_URL: z.string().optional(),
  NEXT_PUBLIC_SEPOLIA_RPC_URL: z.string().optional(),

  NEXT_PUBLIC_LOCAL_SAVING_CIRCLES_CONTRACT_ADDRESS: z.string().optional(),
  NEXT_PUBLIC_LOCAL_SAVING_CIRCLES_VIEWER_CONTRACT_ADDRESS: z
    .string()
    .optional(),
  NEXT_PUBLIC_LOCAL_BREAD_TOKEN_ADDRESS: z.string().optional(),
  NEXT_PUBLIC_LOCAL_DELEGATED_SAVING_CIRCLES_CONTRACT_ADDRESS: z
    .string()
    .optional(),
  NEXT_PUBLIC_LOCAL_SAVING_CIRCLES_CONTRACT_CREATION_BLOCK: z
    .string()
    .optional(),

  NEXT_PUBLIC_SEPOLIA_SAVING_CIRCLES_CONTRACT_ADDRESS: z.string().optional(),
  NEXT_PUBLIC_SEPOLIA_SAVING_CIRCLES_VIEWER_CONTRACT_ADDRESS: z
    .string()
    .optional(),
  NEXT_PUBLIC_SEPOLIA_BREAD_TOKEN_ADDRESS: z.string().optional(),
  NEXT_PUBLIC_SEPOLIA_DELEGATED_SAVING_CIRCLES_CONTRACT_ADDRESS: z
    .string()
    .optional(),
  NEXT_PUBLIC_SEPOLIA_SAVING_CIRCLES_CONTRACT_CREATION_BLOCK: z
    .string()
    .optional(),
  NEXT_PUBLIC_LIT_AUTOPAY_NETWORK: z.string().optional(),
  NEXT_PUBLIC_LIT_AUTOPAY_POLICY_ID: z.string().optional(),

  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: z.string(),
  NEXT_PUBLIC_NODE_ENV: z
    .enum(["development", "production", "local"])
    .default("production"),
  NEXT_PUBLIC_PRIVY_APP_ID: z.string(),
  NEXT_PUBLIC_PRIVY_CLIENT_ID: z.string(),
  NEXT_PUBLIC_ALCHEMY_API_KEY_ETHEREUM_MAINNET: z.string(),
});

const parsedSchema = envSchema.safeParse({
  NEXT_PUBLIC_SAVING_CIRCLES_CONTRACT_ADDRESS:
    process.env.NEXT_PUBLIC_SAVING_CIRCLES_CONTRACT_ADDRESS,
  NEXT_PUBLIC_SAVING_CIRCLES_VIEWER_CONTRACT_ADDRESS:
    process.env.NEXT_PUBLIC_SAVING_CIRCLES_VIEWER_CONTRACT_ADDRESS,
  NEXT_PUBLIC_BREAD_TOKEN_ADDRESS: process.env.NEXT_PUBLIC_BREAD_TOKEN_ADDRESS,
  NEXT_PUBLIC_DELEGATED_SAVING_CIRCLES_CONTRACT_ADDRESS:
    process.env.NEXT_PUBLIC_DELEGATED_SAVING_CIRCLES_CONTRACT_ADDRESS,
  NEXT_PUBLIC_SAVING_CIRCLES_CONTRACT_CREATION_BLOCK:
    process.env.NEXT_PUBLIC_SAVING_CIRCLES_CONTRACT_CREATION_BLOCK,
  NEXT_PUBLIC_TARGET_NETWORK: process.env.NEXT_PUBLIC_TARGET_NETWORK,
  NEXT_PUBLIC_LOCAL_RPC_URL: process.env.NEXT_PUBLIC_LOCAL_RPC_URL,
  NEXT_PUBLIC_GNOSIS_RPC_URL: process.env.NEXT_PUBLIC_GNOSIS_RPC_URL,
  NEXT_PUBLIC_SEPOLIA_RPC_URL: process.env.NEXT_PUBLIC_SEPOLIA_RPC_URL,

  NEXT_PUBLIC_LOCAL_SAVING_CIRCLES_CONTRACT_ADDRESS:
    process.env.NEXT_PUBLIC_LOCAL_SAVING_CIRCLES_CONTRACT_ADDRESS ??
    process.env.NEXT_PUBLIC_SAVING_CIRCLES_CONTRACT_ADDRESS,
  NEXT_PUBLIC_LOCAL_SAVING_CIRCLES_VIEWER_CONTRACT_ADDRESS:
    process.env.NEXT_PUBLIC_LOCAL_SAVING_CIRCLES_VIEWER_CONTRACT_ADDRESS ??
    process.env.NEXT_PUBLIC_SAVING_CIRCLES_VIEWER_CONTRACT_ADDRESS,
  NEXT_PUBLIC_LOCAL_BREAD_TOKEN_ADDRESS:
    process.env.NEXT_PUBLIC_LOCAL_BREAD_TOKEN_ADDRESS ??
    process.env.NEXT_PUBLIC_BREAD_TOKEN_ADDRESS,
  NEXT_PUBLIC_LOCAL_DELEGATED_SAVING_CIRCLES_CONTRACT_ADDRESS:
    process.env.NEXT_PUBLIC_LOCAL_DELEGATED_SAVING_CIRCLES_CONTRACT_ADDRESS ??
    process.env.NEXT_PUBLIC_DELEGATED_SAVING_CIRCLES_CONTRACT_ADDRESS,
  NEXT_PUBLIC_LOCAL_SAVING_CIRCLES_CONTRACT_CREATION_BLOCK:
    process.env.NEXT_PUBLIC_LOCAL_SAVING_CIRCLES_CONTRACT_CREATION_BLOCK ??
    process.env.NEXT_PUBLIC_SAVING_CIRCLES_CONTRACT_CREATION_BLOCK,

  NEXT_PUBLIC_SEPOLIA_SAVING_CIRCLES_CONTRACT_ADDRESS:
    process.env.NEXT_PUBLIC_SEPOLIA_SAVING_CIRCLES_CONTRACT_ADDRESS,
  NEXT_PUBLIC_SEPOLIA_SAVING_CIRCLES_VIEWER_CONTRACT_ADDRESS:
    process.env.NEXT_PUBLIC_SEPOLIA_SAVING_CIRCLES_VIEWER_CONTRACT_ADDRESS,
  NEXT_PUBLIC_SEPOLIA_BREAD_TOKEN_ADDRESS:
    process.env.NEXT_PUBLIC_SEPOLIA_BREAD_TOKEN_ADDRESS,
  NEXT_PUBLIC_SEPOLIA_DELEGATED_SAVING_CIRCLES_CONTRACT_ADDRESS:
    process.env.NEXT_PUBLIC_SEPOLIA_DELEGATED_SAVING_CIRCLES_CONTRACT_ADDRESS,
  NEXT_PUBLIC_SEPOLIA_SAVING_CIRCLES_CONTRACT_CREATION_BLOCK:
    process.env.NEXT_PUBLIC_SEPOLIA_SAVING_CIRCLES_CONTRACT_CREATION_BLOCK,
  NEXT_PUBLIC_LIT_AUTOPAY_NETWORK: process.env.NEXT_PUBLIC_LIT_AUTOPAY_NETWORK,
  NEXT_PUBLIC_LIT_AUTOPAY_POLICY_ID:
    process.env.NEXT_PUBLIC_LIT_AUTOPAY_POLICY_ID,

  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID:
    process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID,
  NEXT_PUBLIC_NODE_ENV: process.env.NEXT_PUBLIC_NODE_ENV,
  NEXT_PUBLIC_PRIVY_APP_ID: process.env.NEXT_PUBLIC_PRIVY_APP_ID,
  NEXT_PUBLIC_PRIVY_CLIENT_ID: process.env.NEXT_PUBLIC_PRIVY_CLIENT_ID,
  NEXT_PUBLIC_ALCHEMY_API_KEY_ETHEREUM_MAINNET:
    process.env.NEXT_PUBLIC_ALCHEMY_API_KEY_ETHEREUM_MAINNET,
});

const requiredByNetwork: Record<
  "local" | "gnosis" | "sepolia",
  (keyof z.infer<typeof envSchema>)[]
> = {
  local: [
    "NEXT_PUBLIC_LOCAL_SAVING_CIRCLES_CONTRACT_ADDRESS",
    "NEXT_PUBLIC_LOCAL_SAVING_CIRCLES_VIEWER_CONTRACT_ADDRESS",
    "NEXT_PUBLIC_LOCAL_BREAD_TOKEN_ADDRESS",
    "NEXT_PUBLIC_LOCAL_SAVING_CIRCLES_CONTRACT_CREATION_BLOCK",
  ],
  gnosis: [
    "NEXT_PUBLIC_SAVING_CIRCLES_CONTRACT_ADDRESS",
    "NEXT_PUBLIC_SAVING_CIRCLES_VIEWER_CONTRACT_ADDRESS",
    "NEXT_PUBLIC_BREAD_TOKEN_ADDRESS",
    "NEXT_PUBLIC_SAVING_CIRCLES_CONTRACT_CREATION_BLOCK",
  ],
  sepolia: [
    "NEXT_PUBLIC_SEPOLIA_SAVING_CIRCLES_CONTRACT_ADDRESS",
    "NEXT_PUBLIC_SEPOLIA_SAVING_CIRCLES_VIEWER_CONTRACT_ADDRESS",
    "NEXT_PUBLIC_SEPOLIA_BREAD_TOKEN_ADDRESS",
    "NEXT_PUBLIC_SEPOLIA_SAVING_CIRCLES_CONTRACT_CREATION_BLOCK",
  ],
};

if (!parsedSchema.success) {
  const errMsg = "___ Provide all CLIENT env variables ___";

  console.log(errMsg);

  console.log(parsedSchema.error.issues);
  throw new Error(errMsg);
}

const validatedEnv = parsedSchema.data;
const selectedNetwork = validatedEnv.NEXT_PUBLIC_TARGET_NETWORK;
const missingRequired = requiredByNetwork[selectedNetwork].filter((key) => {
  const value = validatedEnv[key];
  return !nonEmptyString.safeParse(value).success;
});

if (missingRequired.length > 0) {
  const errMsg = `___ Missing required CLIENT env variables for network "${selectedNetwork}": ${missingRequired.join(", ")} ___`;
  console.log(errMsg);
  throw new Error(errMsg);
}

const selectedNetworkValues = {
  local: {
    NEXT_PUBLIC_SAVING_CIRCLES_CONTRACT_ADDRESS:
      validatedEnv.NEXT_PUBLIC_LOCAL_SAVING_CIRCLES_CONTRACT_ADDRESS!,
    NEXT_PUBLIC_SAVING_CIRCLES_VIEWER_CONTRACT_ADDRESS:
      validatedEnv.NEXT_PUBLIC_LOCAL_SAVING_CIRCLES_VIEWER_CONTRACT_ADDRESS!,
    NEXT_PUBLIC_BREAD_TOKEN_ADDRESS:
      validatedEnv.NEXT_PUBLIC_LOCAL_BREAD_TOKEN_ADDRESS!,
    NEXT_PUBLIC_DELEGATED_SAVING_CIRCLES_CONTRACT_ADDRESS:
      validatedEnv.NEXT_PUBLIC_LOCAL_DELEGATED_SAVING_CIRCLES_CONTRACT_ADDRESS,
    NEXT_PUBLIC_SAVING_CIRCLES_CONTRACT_CREATION_BLOCK:
      validatedEnv.NEXT_PUBLIC_LOCAL_SAVING_CIRCLES_CONTRACT_CREATION_BLOCK!,
  },
  gnosis: {
    NEXT_PUBLIC_SAVING_CIRCLES_CONTRACT_ADDRESS:
      validatedEnv.NEXT_PUBLIC_SAVING_CIRCLES_CONTRACT_ADDRESS,
    NEXT_PUBLIC_SAVING_CIRCLES_VIEWER_CONTRACT_ADDRESS:
      validatedEnv.NEXT_PUBLIC_SAVING_CIRCLES_VIEWER_CONTRACT_ADDRESS,
    NEXT_PUBLIC_BREAD_TOKEN_ADDRESS:
      validatedEnv.NEXT_PUBLIC_BREAD_TOKEN_ADDRESS,
    NEXT_PUBLIC_DELEGATED_SAVING_CIRCLES_CONTRACT_ADDRESS:
      validatedEnv.NEXT_PUBLIC_DELEGATED_SAVING_CIRCLES_CONTRACT_ADDRESS,
    NEXT_PUBLIC_SAVING_CIRCLES_CONTRACT_CREATION_BLOCK:
      validatedEnv.NEXT_PUBLIC_SAVING_CIRCLES_CONTRACT_CREATION_BLOCK,
  },
  sepolia: {
    NEXT_PUBLIC_SAVING_CIRCLES_CONTRACT_ADDRESS:
      validatedEnv.NEXT_PUBLIC_SEPOLIA_SAVING_CIRCLES_CONTRACT_ADDRESS!,
    NEXT_PUBLIC_SAVING_CIRCLES_VIEWER_CONTRACT_ADDRESS:
      validatedEnv.NEXT_PUBLIC_SEPOLIA_SAVING_CIRCLES_VIEWER_CONTRACT_ADDRESS!,
    NEXT_PUBLIC_BREAD_TOKEN_ADDRESS:
      validatedEnv.NEXT_PUBLIC_SEPOLIA_BREAD_TOKEN_ADDRESS!,
    NEXT_PUBLIC_DELEGATED_SAVING_CIRCLES_CONTRACT_ADDRESS:
      validatedEnv.NEXT_PUBLIC_SEPOLIA_DELEGATED_SAVING_CIRCLES_CONTRACT_ADDRESS,
    NEXT_PUBLIC_SAVING_CIRCLES_CONTRACT_CREATION_BLOCK:
      validatedEnv.NEXT_PUBLIC_SEPOLIA_SAVING_CIRCLES_CONTRACT_CREATION_BLOCK!,
  },
}[selectedNetwork];

export const clientEnv = {
  ...validatedEnv,
  ...selectedNetworkValues,
};
