export const dummyStacks = [
	{
		id: "stk-001",
		title: "New Smart TV",
		status: "payment_due",
		progress: 60,
		amount: 10000,
		members: 3,
		breadPerWeek: 50,
		depositAmount: 50,
	},
	{
		id: "stk-002",
		title: "New Home appliances",
		status: "claim",
		progress: 60,
		amount: 400,
		members: 23,
		breadPerWeek: 75,
		claimAmount: 1725,
	},
	{
		id: "stk-003",
		title: "Vacation Fund",
		status: "retired",
		progress: 45,
		amount: 5000,
		members: 8,
		breadPerWeek: 100,
		depositAmount: 100,
	},
	{
		id: "stk-004",
		title: "Gaming Console",
		status: "member",
		progress: 80,
		amount: 600,
		members: 15,
		breadPerWeek: 40,
		claimAmount: 960,
	},
	{
		id: "stk-005",
		title: "Wedding Savings",
		status: "payment_due",
		progress: 30,
		amount: 15000,
		members: 2,
		breadPerWeek: 200,
		depositAmount: 200,
	},
	{
		id: "stk-006",
		title: "Laptop Upgrade",
		status: "member",
		progress: 55,
		amount: 1200,
		members: 12,
		breadPerWeek: 60,
		claimAmount: 840,
	},
	{
		id: "stk-007",
		title: "Car Down Payment",
		status: "payment_due",
		progress: 25,
		amount: 8000,
		members: 5,
		breadPerWeek: 150,
		depositAmount: 150,
	},
	{
		id: "stk-008",
		title: "Home Theater",
		status: "member",
		progress: 70,
		amount: 2500,
		members: 18,
		breadPerWeek: 85,
		claimAmount: 1530,
	},
	{
		id: "stk-009",
		title: "Emergency Fund",
		status: "payment_due",
		progress: 40,
		amount: 3000,
		members: 10,
		breadPerWeek: 75,
		depositAmount: 75,
	},
	{
		id: "stk-010",
		title: "Photography Gear",
		status: "member",
		progress: 90,
		amount: 1800,
		members: 7,
		breadPerWeek: 55,
		claimAmount: 1260,
	},
];
