export const automaticSavingCirclesAbi = [
  {
    type: "function",
    name: "SAVING_CIRCLES",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract ISavingCircles" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "automaticClaimsEnabled",
    inputs: [
      { name: "circleId", type: "uint256", internalType: "uint256" },
      { name: "member", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "enabled", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "automaticDepositsEnabled",
    inputs: [
      { name: "circleId", type: "uint256", internalType: "uint256" },
      { name: "member", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "enabled", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "automationExecutor",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "batchExecuteAutomatedClaims",
    inputs: [
      { name: "_circleIds", type: "uint256[]", internalType: "uint256[]" },
      { name: "_members", type: "address[]", internalType: "address[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "batchExecuteAutomatedDeposits",
    inputs: [
      { name: "_circleIds", type: "uint256[]", internalType: "uint256[]" },
      { name: "_members", type: "address[]", internalType: "address[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "checkUpkeep",
    inputs: [{ name: "", type: "bytes", internalType: "bytes" }],
    outputs: [
      { name: "upkeepNeeded", type: "bool", internalType: "bool" },
      { name: "performData", type: "bytes", internalType: "bytes" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claimChecker",
    inputs: [],
    outputs: [
      { name: "canExec", type: "bool", internalType: "bool" },
      { name: "execPayload", type: "bytes", internalType: "bytes" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "depositChecker",
    inputs: [],
    outputs: [
      { name: "canExec", type: "bool", internalType: "bool" },
      { name: "execPayload", type: "bytes", internalType: "bytes" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "executeAutomatedClaimTarget",
    inputs: [
      { name: "_circleId", type: "uint256", internalType: "uint256" },
      { name: "_member", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "executeAutomatedDepositTarget",
    inputs: [
      { name: "_circleId", type: "uint256", internalType: "uint256" },
      { name: "_member", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getEligibleAutomatedClaims",
    inputs: [],
    outputs: [
      { name: "circleIds", type: "uint256[]", internalType: "uint256[]" },
      { name: "members", type: "address[]", internalType: "address[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEligibleAutomatedDeposits",
    inputs: [],
    outputs: [
      { name: "circleIds", type: "uint256[]", internalType: "uint256[]" },
      { name: "members", type: "address[]", internalType: "address[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isAutomaticClaimsEnabled",
    inputs: [
      { name: "_circleId", type: "uint256", internalType: "uint256" },
      { name: "_member", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isAutomaticDepositsEnabled",
    inputs: [
      { name: "_circleId", type: "uint256", internalType: "uint256" },
      { name: "_member", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "performUpkeep",
    inputs: [{ name: "_performData", type: "bytes", internalType: "bytes" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setAutomaticClaimsEnabled",
    inputs: [
      { name: "_circleId", type: "uint256", internalType: "uint256" },
      { name: "_enabled", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setAutomaticDepositsEnabled",
    inputs: [
      { name: "_circleId", type: "uint256", internalType: "uint256" },
      { name: "_enabled", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setAutomationExecutor",
    inputs: [
      {
        name: "_automationExecutor",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "AutomatedClaimFailed",
    inputs: [
      {
        name: "circleId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "member",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "reason", type: "bytes", indexed: false, internalType: "bytes" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AutomatedDepositFailed",
    inputs: [
      {
        name: "circleId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "member",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "reason", type: "bytes", indexed: false, internalType: "bytes" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AutomaticClaimsToggled",
    inputs: [
      {
        name: "circleId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "member",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "enabled", type: "bool", indexed: true, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AutomaticDepositsToggled",
    inputs: [
      {
        name: "circleId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "member",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "enabled", type: "bool", indexed: true, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AutomationExecutorUpdated",
    inputs: [
      {
        name: "previousExecutor",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newExecutor",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "AlreadyDeposited", inputs: [] },
  { type: "error", name: "ArrayLengthMismatch", inputs: [] },
  { type: "error", name: "AutomaticClaimsDisabled", inputs: [] },
  { type: "error", name: "AutomaticDepositsNotEnabled", inputs: [] },
  { type: "error", name: "CircleNotStarted", inputs: [] },
  { type: "error", name: "CircleTimedOut", inputs: [] },
  { type: "error", name: "DepositBeforeCircleStart", inputs: [] },
  { type: "error", name: "InsufficientAllowance", inputs: [] },
  { type: "error", name: "InsufficientBalance", inputs: [] },
  { type: "error", name: "InvalidPerformData", inputs: [] },
  { type: "error", name: "NotActive", inputs: [] },
  { type: "error", name: "NotMember", inputs: [] },
  { type: "error", name: "NotWithdrawable", inputs: [] },
  { type: "error", name: "OnlyAutomationExecutor", inputs: [] },
  { type: "error", name: "OnlySelf", inputs: [] },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
] as const;
